spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:    resources:      add-mappings: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:travelmap
    driver-class-name: org.h2.Driver
    username: taekrigi
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE