export const TRAVEL_MAP_LIST_REQUEST = 'TRAVEL_MAP_LIST_REQUEST'
export const TRAVEL_MAP_LIST_SUCCESS = 'TRAVEL_MAP_LIST_SUCCESS'
export const TRAVEL_MAP_LIST_FAIL = 'TRAVEL_MAP_LIST_FAIL'
export const TRAVEL_MAP_CLEAR = 'TRAVEL_MAP_CLEAR'

export const DELETE_TRAVEL_MAP_REQUEST = 'DELETE_TRAVEL_MAP_REQUEST'
export const DELETE_TRAVEL_MAP_SUCCESS = 'DELETE_TRAVEL_MAP_SUCCESS'
export const DELETE_TRAVEL_MAP_FAIL = 'DELETE_TRAVEL_MAP_FAIL'

export const VISITED_COUNTRIES_COUNT_REQUEST = 'VISITED_COUNTRIES_COUNT_REQUEST'
export const VISITED_COUNTRIES_COUNT_SUCCESS = 'VISITED_COUNTRIES_COUNT_SUCCESS'
export const VISITED_COUNTRIES_COUNT_FAIL = 'VISITED_COUNTRIES_COUNT_FAIL'
